In [125]:
import numpy as np


def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    # TODO: Compute and return softmax(x)
    
    return np.exp(x) / np.sum(np.exp(x), axis=0)

        



In [126]:
logits = [1.0, 2.0, 3.0]
print(softmax(logits))


[ 0.09003057  0.24472847  0.66524096]


In [127]:
logits = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
print(softmax(logits))

[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [128]:
for c in softmax(logits):
    print(np.sum(c))

0.44166840451
0.713314767018
2.84501682847
